//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanProperties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class PriceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PriceSettings defaultInstance = ((PriceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PriceSettings())));
        
        public static PriceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int PerSquareFeet {
            get {
                return ((int)(this["PerSquareFeet"]));
            }
            set {
                this["PerSquareFeet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PerFloorCost {
            get {
                return ((int)(this["PerFloorCost"]));
            }
            set {
                this["PerFloorCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int PerSeatCost {
            get {
                return ((int)(this["PerSeatCost"]));
            }
            set {
                this["PerSeatCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PerCabinCost {
            get {
                return ((int)(this["PerCabinCost"]));
            }
            set {
                this["PerCabinCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int PerToiletCost {
            get {
                return ((int)(this["PerToiletCost"]));
            }
            set {
                this["PerToiletCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PerKitchenCost {
            get {
                return ((int)(this["PerKitchenCost"]));
            }
            set {
                this["PerKitchenCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int PerRoomCost {
            get {
                return ((int)(this["PerRoomCost"]));
            }
            set {
                this["PerRoomCost"] = value;
            }
        }
    }
}
